language: scala

branches:
  only:
    - master

before_install:
- curl --silent https://shunit2.googlecode.com/files/shunit2-2.1.6.tgz | tar xz -C /tmp/
- git clone https://github.com/ryanbrainard/heroku-buildpack-testrunner.git /tmp/testrunner
- "./etc/hatchet_travis_setup.sh"

install: true

script: "$TEST_CMD"

after_script:
  # just this once
  - heroku keys:clear
  - heroku keys:remove $USER@`hostname`

env:
  global:
  - IS_RUNNING_ON_TRAVIS=true
  - HATCHET_RETRIES=3
  - HATCHET_DEPLOY_STRATEGY=git
  - HATCHET_BUILDPACK_BASE="https://github.com/heroku/heroku-buildpack-scala.git"
  - SHUNIT_HOME="/tmp/shunit2-2.1.6"
  - secure: y5GCEayc55azXFhTgx1J3tqb5YeMTwXqpsvhyzcYUMVU46oHOkc/9KsBM4JQiLqShNqknT4lJwSu13Ra2/9uw8P8CjBdbrCBwfI4+nTdfGjSaX79AM4To7rYSUTpXHrr6YI7HiZemI8VQOjjo/0lsQ4B8qWxv09XevdetPzCmIc=
  matrix:
  - TEST_CMD='[ "$TRAVIS_PULL_REQUEST" = "false" ] && sbt hatchet || true'
  - TEST_CMD="/tmp/testrunner/bin/run -c ."
