[buildpack]
name = "Scala"

  [publish.Ignore]
  files = [
    "etc/",
    "spec/",
    "test/",
    "vendor/",
    ".gitignore",
    ".github/",
    ".travis.yml",
    "circle.yml",
    "hatchet.json",
    "Gemfile",
    "Gemfile.lock",
]
